import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/future/image";
import background from "../public/background.jpg";
import logo from "../public/logo.svg";
import Input from "../components/Input";
import { useState } from "react";

const Home: NextPage = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [checkbox, setCheckbox] = useState(false);

  const handleCheckbox = () => {
    setCheckbox(!checkbox);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Image
        src={logo}
        className='absolute left-8 top-8 w-[120px] z-50 hidden md:block'
      />
      <div className='md:hidden fixed h-16 top-0 left-0 right-0 z-50 bg-white flex items-center'>
        <Image src={logo} className='h-3/5' />
      </div>
      <main className='grid grid-rows-[33%_1fr] md:grid-rows-1 md:grid-cols-[5fr_6fr] w-screen h-screen bg-white justify-items-center items-center relative'>
        <Image
          src={background}
          className='w-full h-full object-cover md:col-start-2'
        />
        <div className='bg-white flex flex-col w-5/6 lg:w-2/3 gap-5 md:row-start-1'>
          <h3 className='text-4xl font-semibold my-4'>Welcome back</h3>
          <Input type='email' name='E-mail' value={email} onChange={setEmail} />
          <Input
            type='password'
            name='Password'
            value={password}
            onChange={setPassword}
          />
          <div className='flex justify-between'>
            <label className='font-medium select-none cursor-pointer'>
              <input
                type='checkbox'
                checked={checkbox}
                onChange={handleCheckbox}
                className='mr-3'
              />
              Remember me
            </label>
            <a className='font-medium' href='/auth'>
              Forgot password?
            </a>
          </div>
          <button className='bg-blue-500 hover:bg-blue-600 text-white font-medium p-3 rounded-xl w-full text-lg transition-all'>
            Sign in
          </button>
          <span className='text-gray-600 text-center mt-2'>
            Don't have an account?{" "}
            <a
              className='font-medium underline hover:text-black transition-all'
              href='/auth'
            >
              Sign up!
            </a>
          </span>
        </div>
      </main>
    </div>
  );
};

export default Home;
