import type { NextPage } from "next";
import Head from "next/head";
import App from "../components/App";
import Auth from "../components/Auth";
import { useAuth } from "../context/AuthContext";

const Home: NextPage = () => {
  const { user } = useAuth();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user ? <App /> : <Auth />}
    </div>
  );
};

export default Home;
